# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Youniverse' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Youniverse
  pod 'SnapKit', '~> 5.0.0'

  target 'YouniverseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YouniverseUITests' do
    # Pods for testing
  end

end
